# Generated by Django 3.2.12 on 2022-03-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_productsgroup'),
        ('sellers', '0002_auto_20220320_0911'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='наименование')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='описание')),
                ('type', models.CharField(choices=[('products_fix_price', 'фиксированная стоимость на товары'), ('products_percent', 'процентная скидка на товары'), ('products_value', 'фиксированная скидка на товары'), ('product_group_fix_price', 'фиксированная стоимость на наборы'), ('product_group_percent', 'процентная скидка на наборы'), ('product_group_value', 'фиксированная скидка на наборы'), ('category_fix_price', 'фиксированная стоимость на категорию товаров'), ('category_percent', 'процентная скидка на категорию товаров'), ('category_value', 'фиксированная скидка на категорию товаров'), ('basket_percent', 'процентная скидка на корзину'), ('basket_value', 'фиксированная скидка на корзину'), ('basket_fix_price', 'фиксированная стоимость на корзину')], max_length=50, verbose_name='тип')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='вес')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='номинал скидки')),
                ('date_from', models.DateField(blank=True, verbose_name='дата начала')),
                ('date_to', models.DateField(verbose_name='дата окончания')),
                ('min_products_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='минимальное количество товаров')),
                ('max_products_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='максимальное количество товаров')),
                ('min_products_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='минимальная цена корзины')),
                ('max_products_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='максимальная цена корзины')),
                ('categories', models.ManyToManyField(blank=True, related_name='discounts', to='categories.Category', verbose_name='категории')),
                ('product_groups', models.ManyToManyField(blank=True, related_name='discounts', to='products.ProductsGroup', verbose_name='группы товаров')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='products.Product', verbose_name='товары')),
                ('seller_products', models.ManyToManyField(blank=True, related_name='discounts', to='sellers.SellerProduct', verbose_name='товары продавцов')),
                ('sub_categories', models.ManyToManyField(blank=True, related_name='discounts', to='categories.SubCategory', verbose_name='подкатегории')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
                'ordering': ('-date_from', 'id'),
            },
        ),
    ]
