# Generated by Django 3.2.12 on 2022-03-14 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='наименование')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='описание')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='индекс сортировки')),
                ('is_limited_edition', models.BooleanField(default=False, verbose_name='ограниченный тираж')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.subcategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('-index',),
            },
        ),
    ]
