# Generated by Django 3.2.12 on 2022-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='наименование')),
                ('products', models.ManyToManyField(blank=True, related_name='groups', to='products.Product', verbose_name='товары')),
            ],
            options={
                'verbose_name': 'группа товаров',
                'verbose_name_plural': 'группы товаров',
                'ordering': ('id',),
            },
        ),
    ]
