# Generated by Django 3.2.12 on 2022-03-11 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_menu', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='время кэширования меню категорий')),
                ('banners', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='время кэширования баннеров')),
                ('seller', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='время кэширования информации о продавцах')),
                ('top_seller_goods', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='время кэширования топа товаров продавца')),
                ('goods_list', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='время кэширования списка товаров')),
                ('detail_page', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='время кэширования детальной страницы')),
            ],
            options={
                'verbose_name': 'время кэширования',
                'verbose_name_plural': 'время кэширований',
            },
        ),
    ]
