# Generated by Django 3.2.12 on 2022-04-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0003_customer'),
        ('sellers', '0004_alter_sellerproduct_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user_app.customer', verbose_name='Покупатель')),
                ('seller_products', models.ManyToManyField(related_name='orders', to='sellers.SellerProduct', verbose_name='Товары продавца')),
            ],
        ),
    ]
