# Generated by Django 3.2.12 on 2022-04-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220409_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_type',
            new_name='delivery_type',
        ),
    ]
