# Generated by Django 3.2.12 on 2022-05-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_seller_email'),
        ('cart', '0003_rename_deliver_type_order_delivery_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_products',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='cart.order', verbose_name='Заказ')),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='sellers.sellerproduct', verbose_name='Товар продавца')),
            ],
        ),
    ]
