# Generated by Django 3.2.12 on 2022-06-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачен'), ('unpaid', 'Не оплачен'), ('canceled', 'Отменен')], default='unpaid', max_length=20, verbose_name='Статус'),
        ),
    ]
