# Generated by Django 3.2.12 on 2022-03-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Описание продавца'),
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя продавца'),
        ),
    ]
