# Generated by Django 3.2.12 on 2022-03-25 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('products', '0001_initial'),
        ('sellers', '0002_auto_20220320_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.AlterModelOptions(
            name='sellerproduct',
            options={'verbose_name': 'Товар продавца', 'verbose_name_plural': 'Товары продавцов'},
        ),
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='user_app.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerproducts', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerproducts', to='sellers.seller', verbose_name='Продавец'),
        ),
    ]
