# Generated by Django 3.2.12 on 2022-04-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsgroup'),
        ('sellers', '0003_auto_20220325_1159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerproduct',
            unique_together={('product', 'seller')},
        ),
    ]
