# Generated by Django 3.2.12 on 2022-04-05 18:52

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='Взрослый да/нет'),
        ),
    ]
