# Generated by Django 3.2.12 on 2022-06-04 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_adult',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Name must be in a format LastName MiddleName[Optional] FirstName. Also make sure your name is written in the same language', regex='^[a-zA-Z]{2,15}\\s[a-zA-Z]{2,15}(?:\\s[a-zA-Z]{2,15})?$|^[а-яА-ЯёЁ]{2,15}\\s[а-яА-ЯёЁ]{2,15}(?:\\s[а-яА-ЯёЁ]{2,15})?$')], verbose_name='ФИO'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number contain ten digits', regex='\\d{10}')], verbose_name='Телефон'),
        ),
    ]
